### ISSUE TITLE
Trigger `add_interest()`, `add_loanlets() and `start()` from the constructor

### ISSUE THREAD

**Issue by jklepatch** [lendingblock/loan-contracts#13]
Currently we need 3 separate transactions to start the loan, and it increases the total transaction cost per loan:

* `constructor()`
* `add_interest()`
* `add_loanlets()`
* `start()`

The `constructor()` could call `add_interest()`, `add_loanlets()` and `start()` itself.

**Comment by QX-Lee** [comment]
the downside is that the arguments into the `constructor` get more complex and there could be too many interest and loanlets to fit in a single transaction

**Comment by QX-Lee** [comment]
current gas analysis for contracts https://github.com/lendingblock/loan-contracts/tree/6535845d5a6693fc52a0d3a0c068f5b82873e459/contracts

```
newLoan(
    [
      '31536000',
      '5000000000',
      '700000000000000000000',
      '1528188800',
      '650000000000000000000',
      '750000000000000000000',
      '1528188800'
    ],
    [
      '0x8f36c426df8f9a808e37a77e4e1e60601fa2c64a97bc31e8072c8945c00eb49d',
      '0x674bdd49be293c9d3bfa46d1836c31b66b7bab28c271ded795a20e2bbc290b23',
      '0x37401b5b342ce644adffa7805ec5aed5510cb290489ff3582d57867f670d12f3',
      '0x7bb540a8208433bafd9e33b6cec4efc8fb482502bef5fe48542f3f6045e7e6af',
      '0xa709fd3aa96d9faf770e44a5aef2f4808a6fe3a5ddf546568f36ad3a3873f31d',
      '0xaad60a3265e1c3c0dff4ef3474d6c608ca5f7ec61bd7dcbc5a992ad057630691',
      '0x425443',
      '0x455448',
    ]
)
```
https://rinkeby.etherscan.io/tx/0x84c1b3d4ba1108af62559df3458d4deac2015764231d425445a792625ed4a30f
gas: 3233149

```
let lenders1 = [];
let lenders2 = [];
for (let i = 0; i < 20; i++) {
    lenders1.push(web3.sha3(i.toString()));
    lenders1.push(web3.sha3((i * 33).toString()));
    lenders1.push(web3.sha3((i * 77).toString()));
    lenders2.push(web3.toBigNumber('700000000000000000000').dividedBy(50).toString());
    lenders2.push(web3.toBigNumber('500').toString());
    lenders2.push(web3.toBigNumber('10000').dividedBy(50).toString());
}
addLenders(lenders1, lenders2)
```
https://rinkeby.etherscan.io/tx/0xe6e7016d8fb42954d5e3ddcc50f02cde725e8adc847423c6bc3a6bccf063ee6c
gas: 2714332

```
let interest1 = [];
let interest2 = [];
for (let i = 0; i < 12; i++) {
    interest1.push(
        web3.toBigNumber('1528188800')
        .add(web3.toBigNumber(i).times('86400').times('30'))
        .toString()
    );
    interest2.push(web3.toBigNumber('10000000000000000000000').toString());
}
addInterest(interest1, interest2)
```
https://rinkeby.etherscan.io/tx/0x20a584d0a79c417c1fe5eb6d32b1f6bec9cef2f18fb608f4af6e2251f0435196
gas: 664096

`start()`
https://rinkeby.etherscan.io/tx/0x911f2ea8f6568de9ef2c2fb509dfa9ae669c6653de15abacb83c2b5237ec21eb
gas: 78273

total gas: 6689850

**Comment by jklepatch** [comment]
Those gas costs are unfortunately way too high. To start a loan, we would fill almost 84% of a block!

Spreadsheet with analysis here:

https://docs.google.com/spreadsheets/d/1WAme_PJmI9rWsv_9MLIEuoV574VQiay1LTNHikawIeU/edit?usp=sharing

**Comment by jklepatch** [comment]
All considered I dont think there is much to be gained from this. We would save the costs of 2 transactions, i.e 42,000 GAS (2 x 21,000). Thats peanuts compared to our gigantic 6.6M gas cost for the whole loan initiation.

**Comment by QX-Lee** [comment]
you might want to take note that the numbers used here (20 lenders, 12 interest payments) might not represent the average type of loans
