### ISSUE TITLE
move functions from loan to loanFactory to reduce gas cost

### ISSUE THREAD

**Issue by QX-Lee** [lendingblock/loan-contracts#16]
since the loans all share the same functions, it might be better to have all the functions in loanFactory instead so creating new loans does not duplicate the functions @jklepatch @theraaz thoughts?

**Comment by jklepatch** [comment]
I agree with the general idea of not duplicating the functions, but I dont think its doable like this. Basically we want these functions to have the same execution context (i.e be able to manipulate the same storage and memory) as those in the `Loan.sol` contract. By putting them into `LoanFactory` it will not be the same execution context.

However by using a library we would have the same execution context.

**Comment by QX-Lee** [comment]
for this gas profile, I have used 5 lenders and 1 interest payment which I think will be the typical loan

basicLoan-initial branch contains the test file for gas profile
https://github.com/lendingblock/loan-contracts/tree/basicLoan-initial

basicLoan-16 branch contains the contracts with functions moved into LoanFactory and test file for gas profile
https://github.com/lendingblock/loan-contracts/tree/basicLoan-16

table shows average gas usage per function call

| function                  | initial   | functions moved to LoanFactory | difference (%) | 
|---------------------------|-----------|--------------------------------|----------------| 
| newLoan                   | 2,315,794 | 1,185,198                      | -48.82%        | 
| addLenders                | 811,018   | 812,680                        | 0.20%          | 
| addInterest               | 92,729    | 94,452                         | 1.86%          | 
| start                     | 78,432    | 105,342                        | 34.31%         | 
| addTransferOutcomeRecords | 129,962   | 131,526                        | 1.20%          | 
| payInterest               | 78,432    | 158,081                        | 101.55%        | 
| interestPaid              | 52,382    | 63,279                         | 20.80%         | 
| mature                    | 40,036    | 62,498                         | 56.10%         | 
| total                     | 3,598,785 | 2,613,056                      | -27.39%        | 

moving functions into LoanFactory reduces the gas for initial deployment of the Loan contract but increases the gas for subsequent function calls as the functions in LoanFactory will need to call the Loan contract compared to just the Loan contract operating by itself
