### ISSUE TITLE
Alternative design: only create events, and dont store data in Loan.sol

### ISSUE THREAD

**Issue by jklepatch** [lendingblock/loan-contracts#19]
If we cant decrease gas cost enough with the optimization of the current implementation, this is an alternative:

* only store the hash of the contract terms
* only send events, and dont store any state variables
* from there, anyone can re-construct the state of the loan by replaying all the events

## Pros:

* smart contract will be more simple
* gas cost will be way less

## Cons:

* external entities have to re-compute the state instead of just reading from the smart contract
* validity of state transitions not enforced by smart contract code anymore

**Comment by lsbardel** [comment]
@jklepatch story points only on epics.
We need to create smaller epics going forward
